import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { db, addDoc, collection, serverTimestamp } from '../services/firebase';
import { useAuth } from '../context/AuthContext';
import { addXP } from '../services/uwCore';

interface Question {
  id: number;
  subject: string;
  text: string;
  options: string[];
  correctOption: number; // 0, 1, 2, 3
  explanation: string;
}

export const RunTestPage: React.FC = () => {
  const navigate = useNavigate();
  const { profile } = useAuth();

  const testName = localStorage.getItem('selectedTestName') || 'JEE Main Mock Test';
  const examType = localStorage.getItem('selectedExam') || 'JEE Main';

  const [questions] = useState<Question[]>([
    {
      id: 1,
      subject: 'Physics',
      text: 'A point charge q is placed at a distance a/2 directly above the centre of a square of side a. The electric flux through the square is:',
      options: ['q / ε₀', 'q / 6ε₀', 'q / 4ε₀', 'q / 2ε₀'],
      correctOption: 1,
      explanation: 'Construct a symmetrical cube of side a enclosing the charge. Total flux through 6 faces is q/ε₀. Hence flux through one square face is q/6ε₀.'
    },
    {
      id: 2,
      subject: 'Physics',
      text: 'A particle executes simple harmonic motion with an amplitude of 5 cm. When the particle is at 3 cm from the mean position, the ratio of its kinetic energy to potential energy is:',
      options: ['16 : 9', '9 : 16', '4 : 3', '3 : 4'],
      correctOption: 0,
      explanation: 'KE = 1/2 k (A² - x²) = 1/2 k (25 - 9) = 16 (in relative units). PE = 1/2 k x² = 9. Ratio = 16:9.'
    },
    {
      id: 3,
      subject: 'Physics',
      text: 'The de-Broglie wavelength of an electron accelerated through a potential difference of V volts is approximately:',
      options: ['12.27 / √V Å', '1.227 / √V nm', '0.286 / √V Å', '0.101 / √V Å'],
      correctOption: 0,
      explanation: 'λ = h / √(2m q V) = 12.27 / √V Angstroms for an electron.'
    },
    {
      id: 4,
      subject: 'Chemistry',
      text: 'Which of the following molecules has zero dipole moment due to symmetric geometry?',
      options: ['NH₃', 'NF₃', 'BF₃', 'H₂O'],
      correctOption: 2,
      explanation: 'BF₃ is trigonal planar (sp² hybridized) with bond angle 120°. The vector sum of dipole moments is exactly zero.'
    },
    {
      id: 5,
      subject: 'Chemistry',
      text: 'The oxidation state of chromium in potassium dichromate (K₂Cr₂O₇) is:',
      options: ['+3', '+4', '+6', '+7'],
      correctOption: 2,
      explanation: '2(+1) + 2(Cr) + 7(-2) = 0 => 2Cr - 12 = 0 => Cr = +6.'
    },
    {
      id: 6,
      subject: 'Chemistry',
      text: 'In the reaction of phenol with chloroform in presence of aqueous NaOH (Reimer-Tiemann reaction), the intermediate formed is:',
      options: ['Carbocation', 'Dichlorocarbene (:CCl₂)', 'Free radical', 'Carbanion'],
      correctOption: 1,
      explanation: 'The electrophile and reactive intermediate is neutral dichlorocarbene (:CCl₂) generated by deprotonation of CHCl₃.'
    },
    {
      id: 7,
      subject: 'Mathematics',
      text: 'The value of the limit lim (x → 0) (sin 3x) / (tan 2x) is equal to:',
      options: ['3 / 2', '2 / 3', '1', '0'],
      correctOption: 0,
      explanation: 'lim (sin 3x / 3x) * (2x / tan 2x) * (3/2) = 1 * 1 * (3/2) = 3/2.'
    },
    {
      id: 8,
      subject: 'Mathematics',
      text: 'If A is a 3 × 3 invertible matrix and |A| = 4, then the determinant of adj(A) is:',
      options: ['4', '16', '64', '1/4'],
      correctOption: 1,
      explanation: '|adj(A)| = |A|^(n - 1). Here n = 3, so |adj(A)| = 4^(3 - 1) = 4² = 16.'
    },
    {
      id: 9,
      subject: 'Mathematics',
      text: 'The order and degree of the differential equation [1 + (dy/dx)²]^(3/2) = d²y/dx² are respectively:',
      options: ['Order 2, Degree 2', 'Order 1, Degree 3', 'Order 2, Degree 3', 'Order 1, Degree 2'],
      correctOption: 0,
      explanation: 'Squaring both sides eliminates the fractional power: [1 + (dy/dx)²]³ = (d²y/dx²)². The highest order derivative is d²y/dx² (Order 2) and its power is 2 (Degree 2).'
    }
  ]);

  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [questionStatus, setQuestionStatus] = useState<Record<number, 'answered' | 'unanswered' | 'review' | 'notvisited'>>({
    0: 'unanswered'
  });
  const [secondsLeft, setSecondsLeft] = useState(180 * 60);
  const [isSubmitOpen, setIsSubmitOpen] = useState(false);
  const [activeSubject, setActiveSubject] = useState('Physics');

  const timerRef = useRef<any>(null);

  useEffect(() => {
    timerRef.current = setInterval(() => {
      setSecondsLeft(prev => {
        if (prev <= 1) {
          clearInterval(timerRef.current);
          submitTest();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(timerRef.current);
  }, []);

  const currentQ = questions[currentIndex];

  const handleSelectOption = (optIdx: number) => {
    setSelectedAnswers(prev => ({ ...prev, [currentIndex]: optIdx }));
  };

  const handleClearResponse = () => {
    const updated = { ...selectedAnswers };
    delete updated[currentIndex];
    setSelectedAnswers(updated);
    setQuestionStatus(prev => ({ ...prev, [currentIndex]: 'unanswered' }));
  };

  const handleSaveAndNext = () => {
    const hasAns = selectedAnswers[currentIndex] !== undefined;
    setQuestionStatus(prev => ({
      ...prev,
      [currentIndex]: hasAns ? 'answered' : 'unanswered'
    }));

    if (currentIndex < questions.length - 1) {
      const nextIdx = currentIndex + 1;
      setCurrentIndex(nextIdx);
      if (!questionStatus[nextIdx]) {
        setQuestionStatus(prev => ({ ...prev, [nextIdx]: 'unanswered' }));
      }
    }
  };

  const handleMarkReviewAndNext = () => {
    setQuestionStatus(prev => ({
      ...prev,
      [currentIndex]: 'review'
    }));

    if (currentIndex < questions.length - 1) {
      const nextIdx = currentIndex + 1;
      setCurrentIndex(nextIdx);
      if (!questionStatus[nextIdx]) {
        setQuestionStatus(prev => ({ ...prev, [nextIdx]: 'unanswered' }));
      }
    }
  };

  const jumpToQuestion = (idx: number) => {
    if (!questionStatus[idx]) {
      setQuestionStatus(prev => ({ ...prev, [idx]: 'unanswered' }));
    }
    setCurrentIndex(idx);
  };

  const submitTest = async () => {
    let score = 0;
    let correctCount = 0;
    let wrongCount = 0;
    let skippedCount = 0;

    const analysisDetails: any[] = [];

    questions.forEach((q, idx) => {
      const userAns = selectedAnswers[idx];
      const isAttempted = userAns !== undefined;
      const isCorrect = userAns === q.correctOption;

      if (isAttempted) {
        if (isCorrect) {
          score += 4;
          correctCount++;
        } else {
          score -= 1;
          wrongCount++;
        }
      } else {
        skippedCount++;
      }

      analysisDetails.push({
        questionId: q.id,
        questionText: q.text,
        subject: q.subject,
        options: q.options,
        userAnswer: userAns ?? null,
        correctOption: q.correctOption,
        isCorrect,
        isAttempted,
        explanation: q.explanation
      });
    });

    const resultPayload = {
      testName,
      examType,
      score,
      maxScore: questions.length * 4,
      totalQuestions: questions.length,
      correctCount,
      wrongCount,
      skippedCount,
      date: new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }),
      analysisDetails
    };

    localStorage.setItem('lastTestResult', JSON.stringify(resultPayload));

    // Award +50 XP for completing a mock test
    await addXP(50);

    // Save to Firestore
    try {
      await addDoc(collection(db, 'mockAttempts'), {
        userId: profile.uid || 'anonymous',
        userName: profile.name || 'Student',
        testName,
        score,
        totalQuestions: questions.length,
        createdAt: serverTimestamp()
      });
    } catch (e) {
      console.warn('Could not save test attempt:', e);
    }

    navigate('/result-summary');
  };

  const formatTimer = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = secs % 60;
    return `${h < 10 ? '0' : ''}${h}:${m < 10 ? '0' : ''}${m}:${s < 10 ? '0' : ''}${s}`;
  };

  const answeredCount = Object.values(questionStatus).filter(s => s === 'answered').length;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', display: 'flex', flexDirection: 'column' }}>
      {/* NTA Top Bar */}
      <div
        style={{
          background: '#0B1220',
          color: '#fff',
          padding: '10px 16px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          borderBottom: '2px solid #1E293B'
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <i className="fa-solid fa-desktop" style={{ color: '#818CF8', fontSize: '16px' }} />
          <div>
            <div style={{ fontSize: '13px', fontWeight: 800 }}>{testName}</div>
            <div style={{ fontSize: '10px', color: '#94A3B8' }}>NTA CBT Live Runner</div>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              background: 'rgba(239,68,68,0.15)',
              border: '1px solid rgba(239,68,68,0.4)',
              padding: '5px 10px',
              borderRadius: '8px',
              color: '#F87171',
              fontFamily: 'monospace',
              fontSize: '14px',
              fontWeight: 700
            }}
          >
            <i className="fa-regular fa-clock" />
            <span>{formatTimer(secondsLeft)}</span>
          </div>

          <button
            onClick={() => setIsSubmitOpen(true)}
            style={{
              padding: '6px 14px',
              borderRadius: '8px',
              background: '#10B981',
              color: '#fff',
              border: 'none',
              fontWeight: 700,
              fontSize: '12.5px',
              cursor: 'pointer'
            }}
          >
            Submit Test
          </button>
        </div>
      </div>

      {/* Subject Filter Tabs */}
      <div
        style={{
          background: 'var(--surface)',
          borderBottom: '1px solid var(--border)',
          padding: '8px 16px',
          display: 'flex',
          gap: '8px'
        }}
      >
        {['Physics', 'Chemistry', 'Mathematics'].map(sub => (
          <button
            key={sub}
            onClick={() => setActiveSubject(sub)}
            style={{
              padding: '6px 14px',
              borderRadius: '8px',
              border: 'none',
              background: activeSubject === sub ? 'var(--accent)' : 'var(--surface2)',
              color: activeSubject === sub ? '#fff' : 'var(--text2)',
              fontSize: '12px',
              fontWeight: 700,
              cursor: 'pointer'
            }}
          >
            {sub}
          </button>
        ))}
      </div>

      {/* Test Runner Body */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', maxWidth: '720px', width: '100%', margin: '0 auto', padding: '14px 16px 80px' }}>
        {/* Question Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
          <span style={{ fontSize: '15px', fontWeight: 800, color: 'var(--text)' }}>
            Question {currentIndex + 1} of {questions.length}
          </span>
          <span style={{ fontSize: '11px', color: '#10B981', fontWeight: 700 }}>
            +4, -1 NTA Marking
          </span>
        </div>

        {/* Question Card */}
        <div
          style={{
            background: 'var(--surface)',
            border: '1.5px solid var(--border)',
            borderRadius: '18px',
            padding: '18px',
            marginBottom: '16px',
            boxShadow: 'var(--shadow-sm)'
          }}
        >
          <div style={{ fontSize: '14px', lineHeight: 1.6, color: 'var(--text)', marginBottom: '18px' }}>
            {currentQ.text}
          </div>

          {/* Options */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {currentQ.options.map((opt, oIdx) => {
              const isSelected = selectedAnswers[currentIndex] === oIdx;
              return (
                <div
                  key={oIdx}
                  onClick={() => handleSelectOption(oIdx)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    padding: '12px 14px',
                    borderRadius: '12px',
                    border: isSelected ? '2px solid var(--accent)' : '1px solid var(--border)',
                    background: isSelected ? 'rgba(91,91,246,0.08)' : 'var(--surface2)',
                    cursor: 'pointer',
                    transition: 'all 0.15s ease'
                  }}
                >
                  <div
                    style={{
                      width: '26px',
                      height: '26px',
                      borderRadius: '50%',
                      background: isSelected ? 'var(--accent)' : 'var(--surface)',
                      border: isSelected ? 'none' : '1.5px solid var(--border)',
                      color: isSelected ? '#fff' : 'var(--text2)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '12px',
                      fontWeight: 700
                    }}
                  >
                    {String.fromCharCode(65 + oIdx)}
                  </div>
                  <div style={{ fontSize: '13px', color: 'var(--text)', fontWeight: isSelected ? 600 : 400 }}>
                    {opt}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Action Controls */}
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '20px' }}>
          <button
            onClick={handleSaveAndNext}
            style={{
              flex: 1,
              padding: '12px',
              borderRadius: '12px',
              background: '#10B981',
              color: '#fff',
              border: 'none',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer'
            }}
          >
            Save &amp; Next
          </button>

          <button
            onClick={handleMarkReviewAndNext}
            style={{
              flex: 1,
              padding: '12px',
              borderRadius: '12px',
              background: '#7C3AED',
              color: '#fff',
              border: 'none',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer'
            }}
          >
            Mark for Review
          </button>

          <button
            onClick={handleClearResponse}
            style={{
              padding: '12px 16px',
              borderRadius: '12px',
              background: 'var(--surface2)',
              color: 'var(--text2)',
              border: '1px solid var(--border)',
              fontWeight: 600,
              fontSize: '13px',
              cursor: 'pointer'
            }}
          >
            Clear
          </button>
        </div>

        {/* Question Palette Grid */}
        <div
          style={{
            background: 'var(--surface)',
            border: '1px solid var(--border)',
            borderRadius: '18px',
            padding: '16px'
          }}
        >
          <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text)', marginBottom: '10px' }}>
            Question Palette ({answeredCount} / {questions.length} Answered)
          </div>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {questions.map((_, pIdx) => {
              const status = questionStatus[pIdx] || 'notvisited';
              const isCurrent = currentIndex === pIdx;

              let bg = 'var(--surface2)';
              let color = 'var(--text2)';
              let border = '1px solid var(--border)';

              if (status === 'answered') {
                bg = '#10B981';
                color = '#fff';
                border = 'none';
              } else if (status === 'unanswered') {
                bg = '#EF4444';
                color = '#fff';
                border = 'none';
              } else if (status === 'review') {
                bg = '#7C3AED';
                color = '#fff';
                border = 'none';
              }

              return (
                <button
                  key={pIdx}
                  onClick={() => jumpToQuestion(pIdx)}
                  style={{
                    width: '36px',
                    height: '36px',
                    borderRadius: '8px',
                    background: bg,
                    color,
                    border: isCurrent ? '2px solid var(--accent)' : border,
                    fontSize: '12.5px',
                    fontWeight: 700,
                    cursor: 'pointer',
                    boxShadow: isCurrent ? '0 0 0 2px var(--accent)' : 'none'
                  }}
                >
                  {pIdx + 1}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Submit Test Confirmation Modal */}
      {isSubmitOpen && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            zIndex: 999999,
            background: 'rgba(0, 0, 0, 0.75)',
            backdropFilter: 'blur(8px)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px'
          }}
        >
          <div
            style={{
              background: 'var(--surface)',
              borderRadius: '24px',
              padding: '28px 22px',
              maxWidth: '360px',
              width: '100%',
              textAlign: 'center',
              border: '1px solid var(--border)',
              boxShadow: '0 24px 60px rgba(0,0,0,0.4)',
              animation: 'appFadeIn 0.25s ease'
            }}
          >
            <div style={{ marginBottom: '12px' }}>
              <i className="fa-solid fa-file-pen" style={{ fontSize: '38px', color: 'var(--accent)' }} />
            </div>
            <h3 style={{ fontSize: '18px', fontWeight: 800, color: 'var(--text)', marginBottom: '8px' }}>
              Submit Your Test?
            </h3>
            <p style={{ fontSize: '13px', color: 'var(--text2)', lineHeight: 1.5, marginBottom: '20px' }}>
              You have answered <strong>{answeredCount}</strong> out of <strong>{questions.length}</strong> questions.
              Once submitted, you will immediately see your score card and AI diagnostic analysis.
            </p>

            <div style={{ display: 'flex', gap: '10px' }}>
              <button
                onClick={() => setIsSubmitOpen(false)}
                style={{
                  flex: 1,
                  padding: '12px',
                  borderRadius: '12px',
                  background: 'var(--surface2)',
                  border: '1px solid var(--border)',
                  color: 'var(--text)',
                  fontWeight: 600,
                  fontSize: '13px',
                  cursor: 'pointer'
                }}
              >
                Keep Solving
              </button>

              <button
                onClick={submitTest}
                style={{
                  flex: 1,
                  padding: '12px',
                  borderRadius: '12px',
                  background: 'linear-gradient(135deg,#5B5BF6,#7C3AED)',
                  border: 'none',
                  color: '#fff',
                  fontWeight: 700,
                  fontSize: '13px',
                  cursor: 'pointer'
                }}
              >
                Yes, Submit
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
